### ISSUE TITLE
Purpose of gcui

### ISSUE THREAD

**Issue by duboisp** [cds-snc/gcui#2]
What is the difference between : 
* [this repository, gcui](https://github.com/cds-snc/gcui)
* [Style defined in WET](https://github.com/wet-boew/wet-boew/tree/master/src/base) like via a personalization of Bootstrap CSS or via the style of individual WET features
* [WET Style guide](http://wet-boew.github.io/wet-boew-styleguide/v4/index-en.html)
* [Canada.ca Style Guide](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-style-guide.html)
* [Common design pattern defined in the Canada.ca Content and IA spec](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification/common-design-patterns.html)
* [GCTools Design system](https://github.com/gctools-outilsgc/design-system)

How they all work together?

**Comment by sleepycat** [comment]
There is definitely some overlap, but the goals are pretty different.
We (CDS) are building Applications (often Single Page Web Applications) and need to generate user interfaces that resemble GoC websites. React is the library we are using, and gcui is a place to put React  components that will be reused across projects.
To the degree that there are aspirations for this project, the aim is to make it possible/easier to create Single Page Apps for use in the GoC.

The WET codebase contains a lot of knowledge about how to create an accessible website, but it's essentially a case of "specification by implementation". If that implementation doesn't work for your case, you are forced to throw baby out with the bathwater.
Gcui attempts to copy both the look and feel of WET while providing an new implementation appropriate for the CDS context: quickly building high quality applications by composing tested ui components.

I can't speak to the goals of the GCTools Design System, but I believe the idea of Design Systems generally is to create not just standards that apply across implementations, but the guides needed to facilitate/inform/encourage the creation of alternate implementations. 

Some of the style guide resources you link to have at least some of the info I would hope for in a design system.

Does that help?

**Comment by sleepycat** [comment]
Closing. Happy to discuss further in the comments.
